version: "3.7"
services:
  db:
    image: postgres:15.4-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", $JAVASTARTER_DATABASE_USER, "-d", $JAVASTARTER_DATABASE_NAME ]
      timeout: 10s
      retries: 10
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data



volumes:
  postgres: