version: "3.7"
services:
  db:
    image: postgres:15.4-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", $POSTGRES_USER, "-d", $POSTGRES_DB ]
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - flightdb:/var/lib/postgresql/data



volumes:
  flightdb: